const ADD_CITY = 'ADD_CITY';
const DELETE_CITY = 'DELETE_CITY';

const FETCHING_WEATHER_DATA = 'FETCHING_WEATHER_DATA';
const FETCHED_WEATHER_DATA = 'FETCHED_WEATHER_DATA';
const ERROR_FETCHING_WEATHER_DATA = 'ERROR_FETCHING_WEATHER_DATA';

const FILTER_BY_CITY_NAME = 'FILTER_BY_CITY_NAME';

export {
    ADD_CITY,
    DELETE_CITY,
    FETCHING_WEATHER_DATA,
    FETCHED_WEATHER_DATA,
    ERROR_FETCHING_WEATHER_DATA,
    FILTER_BY_CITY_NAME
};